import Head from "next/head";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import { sliderData } from "../components/SliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-512x512.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero
        heading="sean photography"
        message="the best photograpyhy in abuja that you can find"
      />
      <Slider sliderData={sliderData} />
    </div>
  );
}
